; NOTE: Assertions have been autogenerated by utils/update_test_checks.py UTC_ARGS: --version 6
; RUN: opt -passes=simplifycfg -S %s | FileCheck %s

; Check that isDereferenceableAndAlignedPointer uses a dereferenceable+align
; assume bundle attached directly to a GEP with a non-constant offset. Without
; that support, the GEP case bails on the non-constant offset and SimplifyCFG
; cannot speculate the load.

define i64 @speculate_load_gep_nonconst_idx(i1 %c, ptr %base, i64 %idx) nosync {
; CHECK-LABEL: define i64 @speculate_load_gep_nonconst_idx(
; CHECK-SAME: i1 [[C:%.*]], ptr [[BASE:%.*]], i64 [[IDX:%.*]]) #[[ATTR0:[0-9]+]] {
; CHECK-NEXT:  [[ENTRY:.*:]]
; CHECK-NEXT:    [[P:%.*]] = getelementptr i8, ptr [[BASE]], i64 [[IDX]]
; CHECK-NEXT:    call void @llvm.assume(i1 true) [ "dereferenceable"(ptr [[P]], i64 8), "align"(ptr [[P]], i64 8) ]
; CHECK-NEXT:    [[V:%.*]] = load i64, ptr [[P]], align 8
; CHECK-NEXT:    [[SPEC_SELECT:%.*]] = select i1 [[C]], i64 [[V]], i64 0
; CHECK-NEXT:    ret i64 [[SPEC_SELECT]]
;
entry:
  %p = getelementptr i8, ptr %base, i64 %idx
  call void @llvm.assume(i1 true) [ "dereferenceable"(ptr %p, i64 8), "align"(ptr %p, i64 8) ]
  br i1 %c, label %if, label %exit

if:
  %v = load i64, ptr %p, align 8
  br label %exit

exit:
  %res = phi i64 [ %v, %if ], [ 0, %entry ]
  ret i64 %res
}
