; NOTE: Assertions have been autogenerated by utils/update_llc_test_checks.py
; RUN: llc -mtriple=aarch64 -O3 %s -o - | FileCheck %s
; RUN: llc -mtriple=aarch64 -O3 -aarch64-enable-widen-cross-block-bool-vec=false %s -o - | FileCheck %s --check-prefix=DISABLE

;; Test that the AArch64WidenBooleanVector pass widens boolean vector
;; operations to avoid unnecessary XTN/SSHLL sequences.

;============================================================================
; Float comparisons: v4i1 -> v4i32 (min 16-bit, using 32-bit source)
;============================================================================

define <4 x float> @test_fcmp_v4_and(<4 x float> %a, <4 x float> %b, <4 x float> %c, <4 x float> %d) {
; CHECK-LABEL: test_fcmp_v4_and:
; CHECK:       // %bb.0: // %entry
; CHECK-NEXT:    fcmge v3.4s, v3.4s, v2.4s
; CHECK-NEXT:    fcmge v1.4s, v1.4s, v0.4s
; CHECK-NEXT:    and v1.16b, v1.16b, v3.16b
; CHECK-NEXT:    bif v0.16b, v2.16b, v1.16b
; CHECK-NEXT:    ret
;
; DISABLE-LABEL: test_fcmp_v4_and:
; DISABLE:       // %bb.0: // %entry
; DISABLE-NEXT:    fcmge v3.4s, v3.4s, v2.4s
; DISABLE-NEXT:    fcmge v1.4s, v1.4s, v0.4s
; DISABLE-NEXT:    and v1.16b, v1.16b, v3.16b
; DISABLE-NEXT:    bif v0.16b, v2.16b, v1.16b
; DISABLE-NEXT:    ret
entry:
  %cmp1 = fcmp ole <4 x float> %a, %b
  %cmp2 = fcmp ole <4 x float> %c, %d
  %and = and <4 x i1> %cmp1, %cmp2
  %sel = select <4 x i1> %and, <4 x float> %a, <4 x float> %c
  ret <4 x float> %sel
}

define <4 x float> @test_fcmp_v4_or(<4 x float> %a, <4 x float> %b, <4 x float> %c, <4 x float> %d) {
; CHECK-LABEL: test_fcmp_v4_or:
; CHECK:       // %bb.0: // %entry
; CHECK-NEXT:    fcmgt v3.4s, v3.4s, v2.4s
; CHECK-NEXT:    fcmgt v1.4s, v1.4s, v0.4s
; CHECK-NEXT:    orr v1.16b, v1.16b, v3.16b
; CHECK-NEXT:    bif v0.16b, v2.16b, v1.16b
; CHECK-NEXT:    ret
;
; DISABLE-LABEL: test_fcmp_v4_or:
; DISABLE:       // %bb.0: // %entry
; DISABLE-NEXT:    fcmgt v3.4s, v3.4s, v2.4s
; DISABLE-NEXT:    fcmgt v1.4s, v1.4s, v0.4s
; DISABLE-NEXT:    orr v1.16b, v1.16b, v3.16b
; DISABLE-NEXT:    bif v0.16b, v2.16b, v1.16b
; DISABLE-NEXT:    ret
entry:
  %cmp1 = fcmp olt <4 x float> %a, %b
  %cmp2 = fcmp olt <4 x float> %c, %d
  %or = or <4 x i1> %cmp1, %cmp2
  %sel = select <4 x i1> %or, <4 x float> %a, <4 x float> %c
  ret <4 x float> %sel
}

define <4 x i32> @test_fcmp_v4_shuffle_splat(<4 x float> %a, <4 x float> %b, <4 x i32> %x, <4 x i32> %y) {
; CHECK-LABEL: test_fcmp_v4_shuffle_splat:
; CHECK:       // %bb.0: // %entry
; CHECK-NEXT:    fcmge v0.4s, v1.4s, v0.4s
; CHECK-NEXT:    dup v0.4s, v0.s[2]
; CHECK-NEXT:    bsl v0.16b, v2.16b, v3.16b
; CHECK-NEXT:    ret
;
; DISABLE-LABEL: test_fcmp_v4_shuffle_splat:
; DISABLE:       // %bb.0: // %entry
; DISABLE-NEXT:    fcmge v0.4s, v1.4s, v0.4s
; DISABLE-NEXT:    dup v0.4s, v0.s[2]
; DISABLE-NEXT:    bsl v0.16b, v2.16b, v3.16b
; DISABLE-NEXT:    ret
entry:
  %cmp = fcmp ole <4 x float> %a, %b
  %splat = shufflevector <4 x i1> %cmp, <4 x i1> poison, <4 x i32> <i32 2, i32 2, i32 2, i32 2>
  %sel = select <4 x i1> %splat, <4 x i32> %x, <4 x i32> %y
  ret <4 x i32> %sel
}

;============================================================================
; Float comparisons: v2i1 -> v2i64 (min 32-bit, using 64-bit source)
;============================================================================

define <2 x double> @test_fcmp_v2_and(<2 x double> %a, <2 x double> %b, <2 x double> %c, <2 x double> %d) {
; CHECK-LABEL: test_fcmp_v2_and:
; CHECK:       // %bb.0: // %entry
; CHECK-NEXT:    fcmge v3.2d, v3.2d, v2.2d
; CHECK-NEXT:    fcmge v1.2d, v1.2d, v0.2d
; CHECK-NEXT:    and v1.16b, v1.16b, v3.16b
; CHECK-NEXT:    bif v0.16b, v2.16b, v1.16b
; CHECK-NEXT:    ret
;
; DISABLE-LABEL: test_fcmp_v2_and:
; DISABLE:       // %bb.0: // %entry
; DISABLE-NEXT:    fcmge v3.2d, v3.2d, v2.2d
; DISABLE-NEXT:    fcmge v1.2d, v1.2d, v0.2d
; DISABLE-NEXT:    and v1.16b, v1.16b, v3.16b
; DISABLE-NEXT:    bif v0.16b, v2.16b, v1.16b
; DISABLE-NEXT:    ret
entry:
  %cmp1 = fcmp ole <2 x double> %a, %b
  %cmp2 = fcmp ole <2 x double> %c, %d
  %and = and <2 x i1> %cmp1, %cmp2
  %sel = select <2 x i1> %and, <2 x double> %a, <2 x double> %c
  ret <2 x double> %sel
}

define <2 x i64> @test_fcmp_v2_shuffle_splat(<2 x double> %a, <2 x double> %b, <2 x i64> %x, <2 x i64> %y) {
; CHECK-LABEL: test_fcmp_v2_shuffle_splat:
; CHECK:       // %bb.0: // %entry
; CHECK-NEXT:    fcmge v0.2d, v1.2d, v0.2d
; CHECK-NEXT:    dup v0.2d, v0.d[0]
; CHECK-NEXT:    bsl v0.16b, v2.16b, v3.16b
; CHECK-NEXT:    ret
;
; DISABLE-LABEL: test_fcmp_v2_shuffle_splat:
; DISABLE:       // %bb.0: // %entry
; DISABLE-NEXT:    fcmge v0.2d, v1.2d, v0.2d
; DISABLE-NEXT:    dup v0.2d, v0.d[0]
; DISABLE-NEXT:    bsl v0.16b, v2.16b, v3.16b
; DISABLE-NEXT:    ret
entry:
  %cmp = fcmp ole <2 x double> %a, %b
  %splat = shufflevector <2 x i1> %cmp, <2 x i1> poison, <2 x i32> <i32 0, i32 0>
  %sel = select <2 x i1> %splat, <2 x i64> %x, <2 x i64> %y
  ret <2 x i64> %sel
}

;============================================================================
; Float comparisons: v8i1 -> v8i16 (min 16-bit, using 16-bit source)
;============================================================================

define <8 x half> @test_fcmp_v8_and(<8 x half> %a, <8 x half> %b, <8 x half> %c, <8 x half> %d) {
; CHECK-LABEL: test_fcmp_v8_and:
; CHECK:       // %bb.0: // %entry
; CHECK-NEXT:    fcvtl2 v4.4s, v1.8h
; CHECK-NEXT:    fcvtl2 v5.4s, v0.8h
; CHECK-NEXT:    fcvtl v6.4s, v0.4h
; CHECK-NEXT:    fcvtl v1.4s, v1.4h
; CHECK-NEXT:    fcvtl2 v7.4s, v2.8h
; CHECK-NEXT:    fcvtl2 v16.4s, v3.8h
; CHECK-NEXT:    fcvtl v17.4s, v2.4h
; CHECK-NEXT:    fcvtl v3.4s, v3.4h
; CHECK-NEXT:    fcmge v4.4s, v4.4s, v5.4s
; CHECK-NEXT:    fcmge v1.4s, v1.4s, v6.4s
; CHECK-NEXT:    fcmge v5.4s, v16.4s, v7.4s
; CHECK-NEXT:    fcmge v3.4s, v3.4s, v17.4s
; CHECK-NEXT:    uzp1 v1.8h, v1.8h, v4.8h
; CHECK-NEXT:    uzp1 v3.8h, v3.8h, v5.8h
; CHECK-NEXT:    and v1.16b, v1.16b, v3.16b
; CHECK-NEXT:    bif v0.16b, v2.16b, v1.16b
; CHECK-NEXT:    ret
;
; DISABLE-LABEL: test_fcmp_v8_and:
; DISABLE:       // %bb.0: // %entry
; DISABLE-NEXT:    fcvtl2 v4.4s, v1.8h
; DISABLE-NEXT:    fcvtl2 v5.4s, v0.8h
; DISABLE-NEXT:    fcvtl v6.4s, v0.4h
; DISABLE-NEXT:    fcvtl v1.4s, v1.4h
; DISABLE-NEXT:    fcvtl2 v7.4s, v2.8h
; DISABLE-NEXT:    fcvtl2 v16.4s, v3.8h
; DISABLE-NEXT:    fcvtl v17.4s, v2.4h
; DISABLE-NEXT:    fcvtl v3.4s, v3.4h
; DISABLE-NEXT:    fcmge v4.4s, v4.4s, v5.4s
; DISABLE-NEXT:    fcmge v1.4s, v1.4s, v6.4s
; DISABLE-NEXT:    fcmge v5.4s, v16.4s, v7.4s
; DISABLE-NEXT:    fcmge v3.4s, v3.4s, v17.4s
; DISABLE-NEXT:    uzp1 v1.8h, v1.8h, v4.8h
; DISABLE-NEXT:    uzp1 v3.8h, v3.8h, v5.8h
; DISABLE-NEXT:    and v1.16b, v1.16b, v3.16b
; DISABLE-NEXT:    bif v0.16b, v2.16b, v1.16b
; DISABLE-NEXT:    ret
entry:
  %cmp1 = fcmp ole <8 x half> %a, %b
  %cmp2 = fcmp ole <8 x half> %c, %d
  %and = and <8 x i1> %cmp1, %cmp2
  %sel = select <8 x i1> %and, <8 x half> %a, <8 x half> %c
  ret <8 x half> %sel
}

;============================================================================
; Integer comparisons: v4i1 -> v4i32 (min 16-bit, using 32-bit source)
;============================================================================

define <4 x i32> @test_icmp_v4_and(<4 x i32> %a, <4 x i32> %b, <4 x i32> %c, <4 x i32> %d) {
; CHECK-LABEL: test_icmp_v4_and:
; CHECK:       // %bb.0: // %entry
; CHECK-NEXT:    cmgt v3.4s, v3.4s, v2.4s
; CHECK-NEXT:    cmgt v1.4s, v1.4s, v0.4s
; CHECK-NEXT:    and v1.16b, v1.16b, v3.16b
; CHECK-NEXT:    bif v0.16b, v2.16b, v1.16b
; CHECK-NEXT:    ret
;
; DISABLE-LABEL: test_icmp_v4_and:
; DISABLE:       // %bb.0: // %entry
; DISABLE-NEXT:    cmgt v3.4s, v3.4s, v2.4s
; DISABLE-NEXT:    cmgt v1.4s, v1.4s, v0.4s
; DISABLE-NEXT:    and v1.16b, v1.16b, v3.16b
; DISABLE-NEXT:    bif v0.16b, v2.16b, v1.16b
; DISABLE-NEXT:    ret
entry:
  %cmp1 = icmp slt <4 x i32> %a, %b
  %cmp2 = icmp slt <4 x i32> %c, %d
  %and = and <4 x i1> %cmp1, %cmp2
  %sel = select <4 x i1> %and, <4 x i32> %a, <4 x i32> %c
  ret <4 x i32> %sel
}

define <4 x i32> @test_icmp_v4_or(<4 x i32> %a, <4 x i32> %b, <4 x i32> %c, <4 x i32> %d) {
; CHECK-LABEL: test_icmp_v4_or:
; CHECK:       // %bb.0: // %entry
; CHECK-NEXT:    cmgt v3.4s, v3.4s, v2.4s
; CHECK-NEXT:    cmgt v1.4s, v1.4s, v0.4s
; CHECK-NEXT:    orr v1.16b, v1.16b, v3.16b
; CHECK-NEXT:    bif v0.16b, v2.16b, v1.16b
; CHECK-NEXT:    ret
;
; DISABLE-LABEL: test_icmp_v4_or:
; DISABLE:       // %bb.0: // %entry
; DISABLE-NEXT:    cmgt v3.4s, v3.4s, v2.4s
; DISABLE-NEXT:    cmgt v1.4s, v1.4s, v0.4s
; DISABLE-NEXT:    orr v1.16b, v1.16b, v3.16b
; DISABLE-NEXT:    bif v0.16b, v2.16b, v1.16b
; DISABLE-NEXT:    ret
entry:
  %cmp1 = icmp slt <4 x i32> %a, %b
  %cmp2 = icmp slt <4 x i32> %c, %d
  %or = or <4 x i1> %cmp1, %cmp2
  %sel = select <4 x i1> %or, <4 x i32> %a, <4 x i32> %c
  ret <4 x i32> %sel
}

define <4 x i32> @test_icmp_v4_xor(<4 x i32> %a, <4 x i32> %b, <4 x i32> %c, <4 x i32> %d) {
; CHECK-LABEL: test_icmp_v4_xor:
; CHECK:       // %bb.0: // %entry
; CHECK-NEXT:    cmgt v3.4s, v3.4s, v2.4s
; CHECK-NEXT:    cmgt v1.4s, v1.4s, v0.4s
; CHECK-NEXT:    eor v1.16b, v1.16b, v3.16b
; CHECK-NEXT:    bif v0.16b, v2.16b, v1.16b
; CHECK-NEXT:    ret
;
; DISABLE-LABEL: test_icmp_v4_xor:
; DISABLE:       // %bb.0: // %entry
; DISABLE-NEXT:    cmgt v3.4s, v3.4s, v2.4s
; DISABLE-NEXT:    cmgt v1.4s, v1.4s, v0.4s
; DISABLE-NEXT:    eor v1.16b, v1.16b, v3.16b
; DISABLE-NEXT:    bif v0.16b, v2.16b, v1.16b
; DISABLE-NEXT:    ret
entry:
  %cmp1 = icmp slt <4 x i32> %a, %b
  %cmp2 = icmp slt <4 x i32> %c, %d
  %xor = xor <4 x i1> %cmp1, %cmp2
  %sel = select <4 x i1> %xor, <4 x i32> %a, <4 x i32> %c
  ret <4 x i32> %sel
}

define <4 x i32> @test_icmp_v4_shuffle_splat(<4 x i32> %a, <4 x i32> %b) {
; CHECK-LABEL: test_icmp_v4_shuffle_splat:
; CHECK:       // %bb.0: // %entry
; CHECK-NEXT:    cmgt v2.4s, v1.4s, v0.4s
; CHECK-NEXT:    dup v2.4s, v2.s[2]
; CHECK-NEXT:    bif v0.16b, v1.16b, v2.16b
; CHECK-NEXT:    ret
;
; DISABLE-LABEL: test_icmp_v4_shuffle_splat:
; DISABLE:       // %bb.0: // %entry
; DISABLE-NEXT:    cmgt v2.4s, v1.4s, v0.4s
; DISABLE-NEXT:    dup v2.4s, v2.s[2]
; DISABLE-NEXT:    bif v0.16b, v1.16b, v2.16b
; DISABLE-NEXT:    ret
entry:
  %cmp = icmp slt <4 x i32> %a, %b
  %splat = shufflevector <4 x i1> %cmp, <4 x i1> poison, <4 x i32> <i32 2, i32 2, i32 2, i32 2>
  %sel = select <4 x i1> %splat, <4 x i32> %a, <4 x i32> %b
  ret <4 x i32> %sel
}

;============================================================================
; Integer comparisons: v2i1 -> v2i64 (min 32-bit, using 64-bit source)
;============================================================================

define <2 x i64> @test_icmp_v2_and(<2 x i64> %a, <2 x i64> %b, <2 x i64> %c, <2 x i64> %d) {
; CHECK-LABEL: test_icmp_v2_and:
; CHECK:       // %bb.0: // %entry
; CHECK-NEXT:    cmgt v3.2d, v3.2d, v2.2d
; CHECK-NEXT:    cmgt v1.2d, v1.2d, v0.2d
; CHECK-NEXT:    and v1.16b, v1.16b, v3.16b
; CHECK-NEXT:    bif v0.16b, v2.16b, v1.16b
; CHECK-NEXT:    ret
;
; DISABLE-LABEL: test_icmp_v2_and:
; DISABLE:       // %bb.0: // %entry
; DISABLE-NEXT:    cmgt v3.2d, v3.2d, v2.2d
; DISABLE-NEXT:    cmgt v1.2d, v1.2d, v0.2d
; DISABLE-NEXT:    and v1.16b, v1.16b, v3.16b
; DISABLE-NEXT:    bif v0.16b, v2.16b, v1.16b
; DISABLE-NEXT:    ret
entry:
  %cmp1 = icmp slt <2 x i64> %a, %b
  %cmp2 = icmp slt <2 x i64> %c, %d
  %and = and <2 x i1> %cmp1, %cmp2
  %sel = select <2 x i1> %and, <2 x i64> %a, <2 x i64> %c
  ret <2 x i64> %sel
}

define <2 x i64> @test_icmp_v2_shuffle_splat(<2 x i64> %a, <2 x i64> %b) {
; CHECK-LABEL: test_icmp_v2_shuffle_splat:
; CHECK:       // %bb.0: // %entry
; CHECK-NEXT:    cmgt v2.2d, v1.2d, v0.2d
; CHECK-NEXT:    dup v2.2d, v2.d[0]
; CHECK-NEXT:    bif v0.16b, v1.16b, v2.16b
; CHECK-NEXT:    ret
;
; DISABLE-LABEL: test_icmp_v2_shuffle_splat:
; DISABLE:       // %bb.0: // %entry
; DISABLE-NEXT:    cmgt v2.2d, v1.2d, v0.2d
; DISABLE-NEXT:    dup v2.2d, v2.d[0]
; DISABLE-NEXT:    bif v0.16b, v1.16b, v2.16b
; DISABLE-NEXT:    ret
entry:
  %cmp = icmp slt <2 x i64> %a, %b
  %splat = shufflevector <2 x i1> %cmp, <2 x i1> poison, <2 x i32> <i32 0, i32 0>
  %sel = select <2 x i1> %splat, <2 x i64> %a, <2 x i64> %b
  ret <2 x i64> %sel
}

;============================================================================
; Integer comparisons: v8i1 -> v8i8/v8i16 (min 8-bit)
;============================================================================

define <8 x i8> @test_icmp_v8i8_and(<8 x i8> %a, <8 x i8> %b, <8 x i8> %c, <8 x i8> %d) {
; CHECK-LABEL: test_icmp_v8i8_and:
; CHECK:       // %bb.0: // %entry
; CHECK-NEXT:    cmgt v3.8b, v3.8b, v2.8b
; CHECK-NEXT:    cmgt v1.8b, v1.8b, v0.8b
; CHECK-NEXT:    and v1.8b, v1.8b, v3.8b
; CHECK-NEXT:    bif v0.8b, v2.8b, v1.8b
; CHECK-NEXT:    ret
;
; DISABLE-LABEL: test_icmp_v8i8_and:
; DISABLE:       // %bb.0: // %entry
; DISABLE-NEXT:    cmgt v3.8b, v3.8b, v2.8b
; DISABLE-NEXT:    cmgt v1.8b, v1.8b, v0.8b
; DISABLE-NEXT:    and v1.8b, v1.8b, v3.8b
; DISABLE-NEXT:    bif v0.8b, v2.8b, v1.8b
; DISABLE-NEXT:    ret
entry:
  %cmp1 = icmp slt <8 x i8> %a, %b
  %cmp2 = icmp slt <8 x i8> %c, %d
  %and = and <8 x i1> %cmp1, %cmp2
  %sel = select <8 x i1> %and, <8 x i8> %a, <8 x i8> %c
  ret <8 x i8> %sel
}

define <8 x i16> @test_icmp_v8i16_and(<8 x i16> %a, <8 x i16> %b, <8 x i16> %c, <8 x i16> %d) {
; CHECK-LABEL: test_icmp_v8i16_and:
; CHECK:       // %bb.0: // %entry
; CHECK-NEXT:    cmgt v3.8h, v3.8h, v2.8h
; CHECK-NEXT:    cmgt v1.8h, v1.8h, v0.8h
; CHECK-NEXT:    and v1.16b, v1.16b, v3.16b
; CHECK-NEXT:    bif v0.16b, v2.16b, v1.16b
; CHECK-NEXT:    ret
;
; DISABLE-LABEL: test_icmp_v8i16_and:
; DISABLE:       // %bb.0: // %entry
; DISABLE-NEXT:    cmgt v3.8h, v3.8h, v2.8h
; DISABLE-NEXT:    cmgt v1.8h, v1.8h, v0.8h
; DISABLE-NEXT:    and v1.16b, v1.16b, v3.16b
; DISABLE-NEXT:    bif v0.16b, v2.16b, v1.16b
; DISABLE-NEXT:    ret
entry:
  %cmp1 = icmp slt <8 x i16> %a, %b
  %cmp2 = icmp slt <8 x i16> %c, %d
  %and = and <8 x i1> %cmp1, %cmp2
  %sel = select <8 x i1> %and, <8 x i16> %a, <8 x i16> %c
  ret <8 x i16> %sel
}

;============================================================================
; Integer comparisons: v16i1 -> v16i8 (min 8-bit)
;============================================================================

define <16 x i8> @test_icmp_v16i8_and(<16 x i8> %a, <16 x i8> %b, <16 x i8> %c, <16 x i8> %d) {
; CHECK-LABEL: test_icmp_v16i8_and:
; CHECK:       // %bb.0: // %entry
; CHECK-NEXT:    cmgt v3.16b, v3.16b, v2.16b
; CHECK-NEXT:    cmgt v1.16b, v1.16b, v0.16b
; CHECK-NEXT:    and v1.16b, v1.16b, v3.16b
; CHECK-NEXT:    bif v0.16b, v2.16b, v1.16b
; CHECK-NEXT:    ret
;
; DISABLE-LABEL: test_icmp_v16i8_and:
; DISABLE:       // %bb.0: // %entry
; DISABLE-NEXT:    cmgt v3.16b, v3.16b, v2.16b
; DISABLE-NEXT:    cmgt v1.16b, v1.16b, v0.16b
; DISABLE-NEXT:    and v1.16b, v1.16b, v3.16b
; DISABLE-NEXT:    bif v0.16b, v2.16b, v1.16b
; DISABLE-NEXT:    ret
entry:
  %cmp1 = icmp slt <16 x i8> %a, %b
  %cmp2 = icmp slt <16 x i8> %c, %d
  %and = and <16 x i1> %cmp1, %cmp2
  %sel = select <16 x i1> %and, <16 x i8> %a, <16 x i8> %c
  ret <16 x i8> %sel
}

define <16 x i8> @test_icmp_v16i8_or(<16 x i8> %a, <16 x i8> %b, <16 x i8> %c, <16 x i8> %d) {
; CHECK-LABEL: test_icmp_v16i8_or:
; CHECK:       // %bb.0: // %entry
; CHECK-NEXT:    cmgt v3.16b, v3.16b, v2.16b
; CHECK-NEXT:    cmgt v1.16b, v1.16b, v0.16b
; CHECK-NEXT:    orr v1.16b, v1.16b, v3.16b
; CHECK-NEXT:    bif v0.16b, v2.16b, v1.16b
; CHECK-NEXT:    ret
;
; DISABLE-LABEL: test_icmp_v16i8_or:
; DISABLE:       // %bb.0: // %entry
; DISABLE-NEXT:    cmgt v3.16b, v3.16b, v2.16b
; DISABLE-NEXT:    cmgt v1.16b, v1.16b, v0.16b
; DISABLE-NEXT:    orr v1.16b, v1.16b, v3.16b
; DISABLE-NEXT:    bif v0.16b, v2.16b, v1.16b
; DISABLE-NEXT:    ret
entry:
  %cmp1 = icmp slt <16 x i8> %a, %b
  %cmp2 = icmp slt <16 x i8> %c, %d
  %or = or <16 x i1> %cmp1, %cmp2
  %sel = select <16 x i1> %or, <16 x i8> %a, <16 x i8> %c
  ret <16 x i8> %sel
}

;============================================================================
; Chain of boolean ops
;============================================================================

define <4 x i32> @test_chain_and_or(<4 x i32> %a, <4 x i32> %b, <4 x i32> %c, <4 x i32> %d, <4 x i32> %e, <4 x i32> %f) {
; CHECK-LABEL: test_chain_and_or:
; CHECK:       // %bb.0: // %entry
; CHECK-NEXT:    cmgt v1.4s, v1.4s, v0.4s
; CHECK-NEXT:    cmgt v3.4s, v3.4s, v2.4s
; CHECK-NEXT:    cmgt v4.4s, v5.4s, v4.4s
; CHECK-NEXT:    and v1.16b, v1.16b, v3.16b
; CHECK-NEXT:    orr v1.16b, v1.16b, v4.16b
; CHECK-NEXT:    bif v0.16b, v2.16b, v1.16b
; CHECK-NEXT:    ret
;
; DISABLE-LABEL: test_chain_and_or:
; DISABLE:       // %bb.0: // %entry
; DISABLE-NEXT:    cmgt v1.4s, v1.4s, v0.4s
; DISABLE-NEXT:    cmgt v3.4s, v3.4s, v2.4s
; DISABLE-NEXT:    cmgt v4.4s, v5.4s, v4.4s
; DISABLE-NEXT:    and v1.16b, v1.16b, v3.16b
; DISABLE-NEXT:    orr v1.16b, v1.16b, v4.16b
; DISABLE-NEXT:    bif v0.16b, v2.16b, v1.16b
; DISABLE-NEXT:    ret
entry:
  %cmp1 = icmp slt <4 x i32> %a, %b
  %cmp2 = icmp slt <4 x i32> %c, %d
  %cmp3 = icmp slt <4 x i32> %e, %f
  %and = and <4 x i1> %cmp1, %cmp2
  %or = or <4 x i1> %and, %cmp3
  %sel = select <4 x i1> %or, <4 x i32> %a, <4 x i32> %c
  ret <4 x i32> %sel
}

;============================================================================
; PHI node tests - boolean vectors flowing through control flow
;============================================================================

; Test PHI node with boolean vector in a simple loop
define <4 x i32> @test_phi_simple_loop(<4 x i32> %a, <4 x i32> %b, <4 x i32> %c, i32 %n) {
; CHECK-LABEL: test_phi_simple_loop:
; CHECK:       // %bb.0: // %entry
; CHECK-NEXT:    cmgt v3.4s, v1.4s, v2.4s
; CHECK-NEXT:    cmgt v1.4s, v1.4s, v0.4s
; CHECK-NEXT:    mov w8, wzr
; CHECK-NEXT:  .LBB17_1: // %loop
; CHECK-NEXT:    // =>This Inner Loop Header: Depth=1
; CHECK-NEXT:    mov v4.16b, v1.16b
; CHECK-NEXT:    and v1.16b, v1.16b, v3.16b
; CHECK-NEXT:    add w8, w8, #1
; CHECK-NEXT:    cmp w8, w0
; CHECK-NEXT:    b.lt .LBB17_1
; CHECK-NEXT:  // %bb.2: // %exit
; CHECK-NEXT:    cmlt v1.4s, v4.4s, #0
; CHECK-NEXT:    bif v0.16b, v2.16b, v1.16b
; CHECK-NEXT:    ret
;
; DISABLE-LABEL: test_phi_simple_loop:
; DISABLE:       // %bb.0: // %entry
; DISABLE-NEXT:    cmgt v3.4s, v1.4s, v2.4s
; DISABLE-NEXT:    cmgt v4.4s, v1.4s, v0.4s
; DISABLE-NEXT:    mov w8, wzr
; DISABLE-NEXT:    xtn v1.4h, v3.4s
; DISABLE-NEXT:    xtn v3.4h, v4.4s
; DISABLE-NEXT:  .LBB17_1: // %loop
; DISABLE-NEXT:    // =>This Inner Loop Header: Depth=1
; DISABLE-NEXT:    fmov d4, d3
; DISABLE-NEXT:    and v3.8b, v3.8b, v1.8b
; DISABLE-NEXT:    add w8, w8, #1
; DISABLE-NEXT:    cmp w8, w0
; DISABLE-NEXT:    b.lt .LBB17_1
; DISABLE-NEXT:  // %bb.2: // %exit
; DISABLE-NEXT:    ushll v1.4s, v4.4h, #0
; DISABLE-NEXT:    shl v1.4s, v1.4s, #31
; DISABLE-NEXT:    cmlt v1.4s, v1.4s, #0
; DISABLE-NEXT:    bif v0.16b, v2.16b, v1.16b
; DISABLE-NEXT:    ret
entry:
  %cmp.init = icmp slt <4 x i32> %a, %b
  br label %loop

loop:
  %i = phi i32 [ 0, %entry ], [ %i.next, %loop ]
  %mask = phi <4 x i1> [ %cmp.init, %entry ], [ %mask.next, %loop ]
  %cmp.loop = icmp sgt <4 x i32> %b, %c
  %mask.next = and <4 x i1> %mask, %cmp.loop
  %i.next = add i32 %i, 1
  %cond = icmp slt i32 %i.next, %n
  br i1 %cond, label %loop, label %exit

exit:
  %sel = select <4 x i1> %mask, <4 x i32> %a, <4 x i32> %c
  ret <4 x i32> %sel
}

; Test PHI node with multiple predecessors
define <4 x i32> @test_phi_diamond(<4 x i32> %a, <4 x i32> %b, <4 x i32> %c, <4 x i32> %d, i1 %cond) {
; CHECK-LABEL: test_phi_diamond:
; CHECK:       // %bb.0: // %entry
; CHECK-NEXT:    tbz w0, #0, .LBB18_2
; CHECK-NEXT:  // %bb.1: // %then
; CHECK-NEXT:    cmgt v1.4s, v1.4s, v0.4s
; CHECK-NEXT:    cmgt v3.4s, v2.4s, v3.4s
; CHECK-NEXT:    and v1.16b, v1.16b, v3.16b
; CHECK-NEXT:    cmlt v1.4s, v1.4s, #0
; CHECK-NEXT:    bif v0.16b, v2.16b, v1.16b
; CHECK-NEXT:    ret
; CHECK-NEXT:  .LBB18_2: // %else
; CHECK-NEXT:    cmge v4.4s, v2.4s, v0.4s
; CHECK-NEXT:    cmge v1.4s, v1.4s, v3.4s
; CHECK-NEXT:    orr v1.16b, v4.16b, v1.16b
; CHECK-NEXT:    cmlt v1.4s, v1.4s, #0
; CHECK-NEXT:    bif v0.16b, v2.16b, v1.16b
; CHECK-NEXT:    ret
;
; DISABLE-LABEL: test_phi_diamond:
; DISABLE:       // %bb.0: // %entry
; DISABLE-NEXT:    cmge v4.4s, v1.4s, v3.4s
; DISABLE-NEXT:    cmge v5.4s, v2.4s, v0.4s
; DISABLE-NEXT:    tst w0, #0x1
; DISABLE-NEXT:    cmgt v1.4s, v1.4s, v0.4s
; DISABLE-NEXT:    cmgt v3.4s, v2.4s, v3.4s
; DISABLE-NEXT:    orr v4.16b, v5.16b, v4.16b
; DISABLE-NEXT:    and v1.16b, v1.16b, v3.16b
; DISABLE-NEXT:    xtn v3.4h, v4.4s
; DISABLE-NEXT:    xtn v1.4h, v1.4s
; DISABLE-NEXT:    fcsel d1, d3, d1, eq
; DISABLE-NEXT:    ushll v1.4s, v1.4h, #0
; DISABLE-NEXT:    shl v1.4s, v1.4s, #31
; DISABLE-NEXT:    cmlt v1.4s, v1.4s, #0
; DISABLE-NEXT:    bif v0.16b, v2.16b, v1.16b
; DISABLE-NEXT:    ret
entry:
  br i1 %cond, label %then, label %else

then:
  %cmp.then = icmp slt <4 x i32> %a, %b
  %cmp.then2 = icmp sgt <4 x i32> %c, %d
  %and.then = and <4 x i1> %cmp.then, %cmp.then2
  br label %merge

else:
  %cmp.else = icmp sle <4 x i32> %a, %c
  %cmp.else2 = icmp sge <4 x i32> %b, %d
  %or.else = or <4 x i1> %cmp.else, %cmp.else2
  br label %merge

merge:
  %mask = phi <4 x i1> [ %and.then, %then ], [ %or.else, %else ]
  %sel = select <4 x i1> %mask, <4 x i32> %a, <4 x i32> %c
  ret <4 x i32> %sel
}

; Test diamond PHI with comparison masks created in if/else blocks
; and one mask selected at exit (no bitwise ops on masks)
declare void @barrier()
define <4 x float> @test_phi_diamond_mask_select(<4 x float> %a, <4 x float> %b, <4 x float> %c, <4 x float> %d, i1 %cond) {
; CHECK-LABEL: test_phi_diamond_mask_select:
; CHECK:       // %bb.0: // %entry
; CHECK-NEXT:    sub sp, sp, #64
; CHECK-NEXT:    str x30, [sp, #48] // 8-byte Spill
; CHECK-NEXT:    .cfi_def_cfa_offset 64
; CHECK-NEXT:    .cfi_offset w30, -16
; CHECK-NEXT:    stp q0, q2, [sp, #16] // 32-byte Folded Spill
; CHECK-NEXT:    tbz w0, #0, .LBB19_2
; CHECK-NEXT:  // %bb.1: // %if.then
; CHECK-NEXT:    str q1, [sp] // 16-byte Spill
; CHECK-NEXT:    bl barrier
; CHECK-NEXT:    ldp q0, q2, [sp] // 32-byte Folded Reload
; CHECK-NEXT:    ldr q1, [sp, #32] // 16-byte Reload
; CHECK-NEXT:    fcmgt v0.4s, v0.4s, v2.4s
; CHECK-NEXT:    cmlt v0.4s, v0.4s, #0
; CHECK-NEXT:    ldr x30, [sp, #48] // 8-byte Reload
; CHECK-NEXT:    bsl v0.16b, v2.16b, v1.16b
; CHECK-NEXT:    add sp, sp, #64
; CHECK-NEXT:    ret
; CHECK-NEXT:  .LBB19_2: // %if.else
; CHECK-NEXT:    str q3, [sp] // 16-byte Spill
; CHECK-NEXT:    bl barrier
; CHECK-NEXT:    ldp q2, q1, [sp, #16] // 32-byte Folded Reload
; CHECK-NEXT:    ldr q0, [sp] // 16-byte Reload
; CHECK-NEXT:    fcmgt v0.4s, v0.4s, v1.4s
; CHECK-NEXT:    cmlt v0.4s, v0.4s, #0
; CHECK-NEXT:    ldr x30, [sp, #48] // 8-byte Reload
; CHECK-NEXT:    bsl v0.16b, v2.16b, v1.16b
; CHECK-NEXT:    add sp, sp, #64
; CHECK-NEXT:    ret
;
; DISABLE-LABEL: test_phi_diamond_mask_select:
; DISABLE:       // %bb.0: // %entry
; DISABLE-NEXT:    sub sp, sp, #64
; DISABLE-NEXT:    str x30, [sp, #48] // 8-byte Spill
; DISABLE-NEXT:    .cfi_def_cfa_offset 64
; DISABLE-NEXT:    .cfi_offset w30, -16
; DISABLE-NEXT:    stp q0, q2, [sp, #16] // 32-byte Folded Spill
; DISABLE-NEXT:    tbz w0, #0, .LBB19_2
; DISABLE-NEXT:  // %bb.1: // %if.then
; DISABLE-NEXT:    str q1, [sp] // 16-byte Spill
; DISABLE-NEXT:    bl barrier
; DISABLE-NEXT:    ldp q0, q2, [sp] // 32-byte Folded Reload
; DISABLE-NEXT:    ldr q1, [sp, #32] // 16-byte Reload
; DISABLE-NEXT:    fcmgt v0.4s, v0.4s, v2.4s
; DISABLE-NEXT:    b .LBB19_3
; DISABLE-NEXT:  .LBB19_2: // %if.else
; DISABLE-NEXT:    str q3, [sp] // 16-byte Spill
; DISABLE-NEXT:    bl barrier
; DISABLE-NEXT:    ldp q2, q1, [sp, #16] // 32-byte Folded Reload
; DISABLE-NEXT:    ldr q0, [sp] // 16-byte Reload
; DISABLE-NEXT:    fcmgt v0.4s, v0.4s, v1.4s
; DISABLE-NEXT:  .LBB19_3: // %exit
; DISABLE-NEXT:    xtn v0.4h, v0.4s
; DISABLE-NEXT:    ushll v0.4s, v0.4h, #0
; DISABLE-NEXT:    ldr x30, [sp, #48] // 8-byte Reload
; DISABLE-NEXT:    shl v0.4s, v0.4s, #31
; DISABLE-NEXT:    cmlt v0.4s, v0.4s, #0
; DISABLE-NEXT:    bsl v0.16b, v2.16b, v1.16b
; DISABLE-NEXT:    add sp, sp, #64
; DISABLE-NEXT:    ret
entry:
  br i1 %cond, label %if.then, label %if.else, !unpredictable !0

if.then:
  call void @barrier() #0
  %mask.then = fcmp olt <4 x float> %a, %b
  br label %exit

if.else:
  call void @barrier() #0
  %mask.else = fcmp olt <4 x float> %c, %d
  br label %exit

exit:
  %mask = phi <4 x i1> [ %mask.then, %if.then ], [ %mask.else, %if.else ]
  %sel = select <4 x i1> %mask, <4 x float> %a, <4 x float> %c
  ret <4 x float> %sel
}

attributes #0 = { convergent }

; Test double-wide PHI node (v2i64)
define <2 x i64> @test_phi_v2i64_loop(<2 x i64> %a, <2 x i64> %b, <2 x i64> %c, i32 %n) {
; CHECK-LABEL: test_phi_v2i64_loop:
; CHECK:       // %bb.0: // %entry
; CHECK-NEXT:    cmgt v3.2d, v1.2d, v2.2d
; CHECK-NEXT:    cmgt v1.2d, v1.2d, v0.2d
; CHECK-NEXT:    mov w8, wzr
; CHECK-NEXT:  .LBB20_1: // %loop
; CHECK-NEXT:    // =>This Inner Loop Header: Depth=1
; CHECK-NEXT:    mov v4.16b, v1.16b
; CHECK-NEXT:    orr v1.16b, v1.16b, v3.16b
; CHECK-NEXT:    add w8, w8, #1
; CHECK-NEXT:    cmp w8, w0
; CHECK-NEXT:    b.lt .LBB20_1
; CHECK-NEXT:  // %bb.2: // %exit
; CHECK-NEXT:    cmlt v1.2d, v4.2d, #0
; CHECK-NEXT:    bif v0.16b, v2.16b, v1.16b
; CHECK-NEXT:    ret
;
; DISABLE-LABEL: test_phi_v2i64_loop:
; DISABLE:       // %bb.0: // %entry
; DISABLE-NEXT:    cmgt v3.2d, v1.2d, v2.2d
; DISABLE-NEXT:    cmgt v4.2d, v1.2d, v0.2d
; DISABLE-NEXT:    mov w8, wzr
; DISABLE-NEXT:    xtn v1.2s, v3.2d
; DISABLE-NEXT:    xtn v3.2s, v4.2d
; DISABLE-NEXT:  .LBB20_1: // %loop
; DISABLE-NEXT:    // =>This Inner Loop Header: Depth=1
; DISABLE-NEXT:    fmov d4, d3
; DISABLE-NEXT:    orr v3.8b, v3.8b, v1.8b
; DISABLE-NEXT:    add w8, w8, #1
; DISABLE-NEXT:    cmp w8, w0
; DISABLE-NEXT:    b.lt .LBB20_1
; DISABLE-NEXT:  // %bb.2: // %exit
; DISABLE-NEXT:    ushll v1.2d, v4.2s, #0
; DISABLE-NEXT:    shl v1.2d, v1.2d, #63
; DISABLE-NEXT:    cmlt v1.2d, v1.2d, #0
; DISABLE-NEXT:    bif v0.16b, v2.16b, v1.16b
; DISABLE-NEXT:    ret
entry:
  %cmp.init = icmp slt <2 x i64> %a, %b
  br label %loop

loop:
  %i = phi i32 [ 0, %entry ], [ %i.next, %loop ]
  %mask = phi <2 x i1> [ %cmp.init, %entry ], [ %mask.next, %loop ]
  %cmp.loop = icmp sgt <2 x i64> %b, %c
  %mask.next = or <2 x i1> %mask, %cmp.loop
  %i.next = add i32 %i, 1
  %cond = icmp slt i32 %i.next, %n
  br i1 %cond, label %loop, label %exit

exit:
  %sel = select <2 x i1> %mask, <2 x i64> %a, <2 x i64> %c
  ret <2 x i64> %sel
}

;============================================================================
; Negative tests - should not transform
;============================================================================

; Simple compare->select without boolean ops should not be transformed
define <4 x i32> @test_simple_compare_select(<4 x i32> %a, <4 x i32> %b) {
; CHECK-LABEL: test_simple_compare_select:
; CHECK:       // %bb.0: // %entry
; CHECK-NEXT:    smin v0.4s, v0.4s, v1.4s
; CHECK-NEXT:    ret
;
; DISABLE-LABEL: test_simple_compare_select:
; DISABLE:       // %bb.0: // %entry
; DISABLE-NEXT:    smin v0.4s, v0.4s, v1.4s
; DISABLE-NEXT:    ret
entry:
  %cmp = icmp slt <4 x i32> %a, %b
  %sel = select <4 x i1> %cmp, <4 x i32> %a, <4 x i32> %b
  ret <4 x i32> %sel
}

!0 = !{}
